sudo: false
language: python
python:
    - "2.7"

before_install:
  # Setup miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  # Create a virtual environment with the right version of python
  - conda create -n testing python=$TRAVIS_PYTHON_VERSION --yes
  - source activate testing

# Install packages
install:
  - conda install --yes -c conda-forge mpi4py openmpi
script:
  - "mpirun -np 2 python -c 'from mpi4py import MPI'"